spring:
  application:
    name: dynamic-threadpool-example

  profiles:
    active: dev

  dynamic:
    thread-pool:
      server-addr: http://localhost:6691
      tenantId: common
      item-id: dtp

server:
  port: 8088
  servlet:
    context-path: /example
