spring:
  application:
    name: dtp

  profiles:
    active: dev

  dynamic:
    thread-pool:
      server-addr: http://localhost:6691
      tenantId: common
      item-id: ${spring.application.name}

server:
  port: 8088
  servlet:
    context-path: /example
